id: P1B88E6B8
initial_creation_type: input
source_metadata:
  title: Seventh Dalai Lama Series
  language: en
  description: 'Texts by the Seventh Dalai Lama, Kalzang Gyatso (skal bzang rgya mtsho,
    1708–1757):'
  volume:
    7b0b7d6f4fc64dfc9f760d17fa287182:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      parent: Songs
created_at: '2022-03-01T01:30:32.331231'
last_modified_at: '2022-03-01T01:30:32.331237'
